import { useState, useEffect } from 'react';
import Head from 'next/head';
import DefaultLayout from '../../layouts/Default';
import Card from '../../components/Card';

export default function Cities() {

  const [cities, setCities] = useState([])

  const fetchCities = async () => {
    const response = await fetch('/api/cities');
    const data = await response.json();
    setCities(data);
  }

    useEffect(() => {
      fetchCities();
    }, [])
  

  return (
    <>
      <Head>
        <title>Top 10 American Cities</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DefaultLayout>
        <div className="container mt-5">
            <div style={{ 
                display: "flex", 
                justifyContent: "center",
                alignItems: "center",
                flexWrap: "wrap"
            }}>
            {cities.map(city => (
              <Card 
                key={city.id}
                img={city.img}
                alt={city.alt}
                name={city.name} 
                state={city.state}
                population={city.population}
                />
            ))}
            </div>
        </div>
      </DefaultLayout>
    </>  
  );
}

