import Head from 'next/head'
import Nav from '../components/Nav'
import Jumbotron from '../components/Jumbotron';
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sports Leagues</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
 
      <main>
        <Nav />
        <Jumbotron />
      </main>
    </div>
  )
}
