import Head from 'next/head'
import Nav from '../components/Nav'
import Jumbotron from '../components/Jumbotron';

export default function Home() {
  return (
    <div>
      <Head>
        <title>American Cities</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
 
      <main>
        <Nav />
        <Jumbotron />
      </main>
    </div>
  )
}
