import Head from 'next/head'
import DefaultLayout from '../layouts/Default';
import Jumbotron from '../components/Jumbotron';

export default function Home() {
  return (
    <div>
      <Head>
        <title>American Cities</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
 
      <DefaultLayout>
        <Jumbotron />
      </DefaultLayout>
    </div>
  )
}
